### ISSUE TITLE
Thank you for this great app but it doesn't work.

### ISSUE THREAD

**Issue by JohnClaw** [flatsiedatsie/transformers_js_musicgen#1]
Nothing happens after i press "Generate" button. No CPU or GPU activity. Where does it save downloaded model and generated wav file? What web-browser does it need to run? Can it run in cpu-only mode? Can it run offline?

**Comment by flatsiedatsie** [comment]
Thanks, I fixed it.

> Where does it save downloaded model

In the browser cache. You can clear it manually, or your browser will delete it automatically if disk space is getting low.

> and generated wav file?

You can save that to disk when it's done generating the  audio by right-clicking on the audio player/clicking on the audio player's three dots menu (depends on your browser).

> Can it run in cpu-only mode? 

That's actually what it does at the moment, until Transformers.js V3 is fully ready.

> Can it run offline?

Once the model is downloaded you can switch off wifi and continue generating music, yes. You could technically even make the website always be available, even when already offline, by using a [service worker](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers). That would turn the website into something of an always available app.

I'll be revealing something that does all this soon, so I wouldn't worry about building it yourself :-)
